// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: blog/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetInforRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetInforRequest) Reset()         { *m = QueryGetInforRequest{} }
func (m *QueryGetInforRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetInforRequest) ProtoMessage()    {}
func (*QueryGetInforRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e22cd6d352f3384, []int{0}
}
func (m *QueryGetInforRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetInforRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetInforRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetInforRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetInforRequest.Merge(m, src)
}
func (m *QueryGetInforRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetInforRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetInforRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetInforRequest proto.InternalMessageInfo

func (m *QueryGetInforRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetInforResponse struct {
	Infor *Infor `protobuf:"bytes,1,opt,name=Infor,proto3" json:"Infor,omitempty"`
}

func (m *QueryGetInforResponse) Reset()         { *m = QueryGetInforResponse{} }
func (m *QueryGetInforResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetInforResponse) ProtoMessage()    {}
func (*QueryGetInforResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e22cd6d352f3384, []int{1}
}
func (m *QueryGetInforResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetInforResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetInforResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetInforResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetInforResponse.Merge(m, src)
}
func (m *QueryGetInforResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetInforResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetInforResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetInforResponse proto.InternalMessageInfo

func (m *QueryGetInforResponse) GetInfor() *Infor {
	if m != nil {
		return m.Infor
	}
	return nil
}

type QueryAllInforRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllInforRequest) Reset()         { *m = QueryAllInforRequest{} }
func (m *QueryAllInforRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllInforRequest) ProtoMessage()    {}
func (*QueryAllInforRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e22cd6d352f3384, []int{2}
}
func (m *QueryAllInforRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllInforRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllInforRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllInforRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllInforRequest.Merge(m, src)
}
func (m *QueryAllInforRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllInforRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllInforRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllInforRequest proto.InternalMessageInfo

func (m *QueryAllInforRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllInforResponse struct {
	Infor      []*Infor            `protobuf:"bytes,1,rep,name=Infor,proto3" json:"Infor,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllInforResponse) Reset()         { *m = QueryAllInforResponse{} }
func (m *QueryAllInforResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllInforResponse) ProtoMessage()    {}
func (*QueryAllInforResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e22cd6d352f3384, []int{3}
}
func (m *QueryAllInforResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllInforResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllInforResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllInforResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllInforResponse.Merge(m, src)
}
func (m *QueryAllInforResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllInforResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllInforResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllInforResponse proto.InternalMessageInfo

func (m *QueryAllInforResponse) GetInfor() []*Infor {
	if m != nil {
		return m.Infor
	}
	return nil
}

func (m *QueryAllInforResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetInforRequest)(nil), "example.blog.blog.QueryGetInforRequest")
	proto.RegisterType((*QueryGetInforResponse)(nil), "example.blog.blog.QueryGetInforResponse")
	proto.RegisterType((*QueryAllInforRequest)(nil), "example.blog.blog.QueryAllInforRequest")
	proto.RegisterType((*QueryAllInforResponse)(nil), "example.blog.blog.QueryAllInforResponse")
}

func init() { proto.RegisterFile("blog/query.proto", fileDescriptor_6e22cd6d352f3384) }

var fileDescriptor_6e22cd6d352f3384 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4b, 0xf3, 0x30,
	0x1c, 0xc6, 0xd7, 0xbe, 0xef, 0x5e, 0x5e, 0x22, 0x88, 0x06, 0x85, 0x51, 0xb4, 0x8e, 0xa2, 0xdb,
	0xf0, 0x90, 0xb0, 0x79, 0x17, 0xe6, 0xc1, 0xe1, 0x4d, 0x77, 0xf4, 0x20, 0xa4, 0x5b, 0xac, 0x81,
	0xac, 0xe9, 0x96, 0x4c, 0x36, 0x44, 0x44, 0xcf, 0x1e, 0x06, 0xfe, 0x53, 0x1e, 0x07, 0x5e, 0x3c,
	0xca, 0xe6, 0x1f, 0x22, 0x4d, 0x02, 0xfb, 0xcd, 0xbc, 0xb4, 0xf0, 0xed, 0xf3, 0xe4, 0xf9, 0x7c,
	0xf3, 0x14, 0x6c, 0x85, 0x5c, 0x44, 0xb8, 0xdd, 0xa5, 0x9d, 0x3e, 0x4a, 0x3a, 0x42, 0x09, 0xb8,
	0x4d, 0x7b, 0xa4, 0x95, 0x70, 0x8a, 0xd2, 0x2f, 0xfa, 0xe1, 0xed, 0x45, 0x42, 0x44, 0x9c, 0x62,
	0x92, 0x30, 0x4c, 0xe2, 0x58, 0x28, 0xa2, 0x98, 0x88, 0xa5, 0x31, 0x78, 0xc7, 0x0d, 0x21, 0x5b,
	0x42, 0xe2, 0x90, 0x48, 0x6a, 0x4e, 0xc2, 0xf7, 0xe5, 0x90, 0x2a, 0x52, 0xc6, 0x09, 0x89, 0x58,
	0xac, 0xc5, 0x56, 0x6b, 0xe2, 0x58, 0x7c, 0x2b, 0x3a, 0x66, 0x12, 0x14, 0xc0, 0xce, 0x55, 0xea,
	0xa9, 0x51, 0x75, 0x91, 0x8e, 0xeb, 0xb4, 0xdd, 0xa5, 0x52, 0xc1, 0x4d, 0xe0, 0xb2, 0x66, 0xce,
	0xc9, 0x3b, 0xa5, 0xbf, 0x75, 0x97, 0x35, 0x83, 0x1a, 0xd8, 0x9d, 0xd3, 0xc9, 0x44, 0xc4, 0x92,
	0x42, 0x04, 0xb2, 0x7a, 0xa0, 0xb5, 0x1b, 0x95, 0x1c, 0x5a, 0xe0, 0x47, 0xc6, 0x60, 0x64, 0xc1,
	0x8d, 0x0d, 0xac, 0x72, 0x3e, 0x13, 0x78, 0x0e, 0xc0, 0x04, 0xd7, 0x1e, 0x56, 0x40, 0x66, 0x37,
	0x94, 0xee, 0x86, 0xcc, 0x2d, 0xd9, 0xdd, 0xd0, 0x25, 0x89, 0xa8, 0xf5, 0xd6, 0xa7, 0x9c, 0xc1,
	0xc0, 0xb1, 0xa4, 0x93, 0x80, 0x45, 0xd2, 0x3f, 0xbf, 0x20, 0x85, 0xb5, 0x19, 0x22, 0x57, 0x13,
	0x15, 0xd7, 0x12, 0x99, 0xb0, 0x69, 0xa4, 0xca, 0xab, 0x0b, 0xb2, 0x1a, 0x09, 0x3e, 0x3b, 0x96,
	0x01, 0x16, 0x97, 0xa4, 0x2f, 0x2b, 0xc2, 0x2b, 0xad, 0x17, 0x9a, 0xc8, 0xe0, 0xe8, 0xe5, 0xe3,
	0xfb, 0xcd, 0x3d, 0x80, 0xfb, 0xd8, 0x3a, 0xb0, 0x6e, 0x7b, 0x52, 0x39, 0x7e, 0x60, 0xcd, 0x47,
	0xf8, 0x04, 0xfe, 0x6b, 0x5f, 0x95, 0xf3, 0xd5, 0x14, 0x73, 0xed, 0xac, 0xa6, 0x98, 0xbf, 0xe5,
	0x20, 0xaf, 0x29, 0x3c, 0x98, 0x5b, 0x45, 0x71, 0x76, 0xfa, 0x3e, 0xf2, 0x9d, 0xe1, 0xc8, 0x77,
	0xbe, 0x46, 0xbe, 0x33, 0x18, 0xfb, 0x99, 0xe1, 0xd8, 0xcf, 0x7c, 0x8e, 0xfd, 0xcc, 0xf5, 0x61,
	0xc4, 0xd4, 0x5d, 0x37, 0x44, 0x0d, 0xd1, 0x9a, 0x75, 0xf7, 0xcc, 0x4b, 0xf5, 0x13, 0x2a, 0xc3,
	0x7f, 0xfa, 0xcf, 0x3d, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x84, 0xf9, 0xdf, 0x3c, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// this line is used by starport scaffolding # 2
	Infor(ctx context.Context, in *QueryGetInforRequest, opts ...grpc.CallOption) (*QueryGetInforResponse, error)
	InforAll(ctx context.Context, in *QueryAllInforRequest, opts ...grpc.CallOption) (*QueryAllInforResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Infor(ctx context.Context, in *QueryGetInforRequest, opts ...grpc.CallOption) (*QueryGetInforResponse, error) {
	out := new(QueryGetInforResponse)
	err := c.cc.Invoke(ctx, "/example.blog.blog.Query/Infor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) InforAll(ctx context.Context, in *QueryAllInforRequest, opts ...grpc.CallOption) (*QueryAllInforResponse, error) {
	out := new(QueryAllInforResponse)
	err := c.cc.Invoke(ctx, "/example.blog.blog.Query/InforAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// this line is used by starport scaffolding # 2
	Infor(context.Context, *QueryGetInforRequest) (*QueryGetInforResponse, error)
	InforAll(context.Context, *QueryAllInforRequest) (*QueryAllInforResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Infor(ctx context.Context, req *QueryGetInforRequest) (*QueryGetInforResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Infor not implemented")
}
func (*UnimplementedQueryServer) InforAll(ctx context.Context, req *QueryAllInforRequest) (*QueryAllInforResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InforAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Infor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetInforRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Infor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.blog.blog.Query/Infor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Infor(ctx, req.(*QueryGetInforRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_InforAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllInforRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).InforAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.blog.blog.Query/InforAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).InforAll(ctx, req.(*QueryAllInforRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.blog.blog.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Infor",
			Handler:    _Query_Infor_Handler,
		},
		{
			MethodName: "InforAll",
			Handler:    _Query_InforAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog/query.proto",
}

func (m *QueryGetInforRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetInforRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetInforRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetInforResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetInforResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetInforResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Infor != nil {
		{
			size, err := m.Infor.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllInforRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllInforRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllInforRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllInforResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllInforResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllInforResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Infor) > 0 {
		for iNdEx := len(m.Infor) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Infor[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetInforRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetInforResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Infor != nil {
		l = m.Infor.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllInforRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllInforResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Infor) > 0 {
		for _, e := range m.Infor {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetInforRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetInforRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetInforRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetInforResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetInforResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetInforResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Infor", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Infor == nil {
				m.Infor = &Infor{}
			}
			if err := m.Infor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllInforRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllInforRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllInforRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllInforResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllInforResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllInforResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Infor", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Infor = append(m.Infor, &Infor{})
			if err := m.Infor[len(m.Infor)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
